In [23]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from PIL import Image
from glob import glob
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
import os
from tqdm.notebook import tqdm_notebook

In [24]:
plt.rcParams['font.family']=['Heiti TC']
plt.rcParams['figure.figsize']=(20,10)

In [25]:
image_list = glob('tutorial/chapter9/demo/data/images/*.jpg')

In [26]:
n = len(image_list)
features = np.zeros([n,9])
labels = np.zeros([n])

In [27]:
image = Image.open(image_list[0])

In [28]:
r,g,b=image.split()

In [29]:
r=(np.asarray(r)/255)

In [30]:
r.mean(),r.std()

(0.5145421407845159, 0.0860573283455072)

In [31]:
def third_var(data):
    x = np.mean((data-data.mean())**3)
    return np.sign(x)*(abs(x))**(1/3)

In [32]:
i = 0
for img_file in tqdm_notebook(image_list):
    image = Image.open(img_file)
    w,h = image.size
    image = image.crop((w/2-50,h/2-50,w/2+50,h/2+50))
    r,g,b = image.split()
    r,g,b = np.asarray(r)/255,np.asarray(g)/255,np.asarray(b)/255
    features[i,0:3] = r.mean(),g.mean(),b.mean()
    features[i,3:6] = r.std(),g.std(),b.std()
    features[i,6:9] = third_var(r),third_var(g),third_var(b)
    labels[i]= os.path.basename(img_file)[0]
    i+=1

  0%|          | 0/203 [00:00<?, ?it/s]

In [33]:
data_train,data_test,label_train,label_test = train_test_split(features,labels,test_size=0.2,random_state=10)

In [34]:
model = DecisionTreeClassifier(random_state=5).fit(data_train,label_train)

In [35]:
predict=model.predict(data_test)

In [36]:
cm = confusion_matrix(label_test,predict)
print(cm)

[[11  1  1  0  0]
 [ 0  9  0  0  0]
 [ 0  0 12  0  0]
 [ 0  1  0  3  1]
 [ 0  0  0  0  2]]


In [37]:
print(accuracy_score(label_test,predict))

0.9024390243902439
